//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInformation
    {
        public string Номерной_знак { get; set; }
        public string Статус_авто { get; set; }
        public string Модель_авто { get; set; }
        public string Марка_авто { get; set; }
    }
}
