//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string Имя_клиента { get; set; }
        public string Номер_телефона { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Статус_аренды { get; set; }
    }
}
