//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtoParkEntities : DbContext
    {
        public AvtoParkEntities()
            : base("name=AvtoParkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Автомобиль> Автомобиль { get; set; }
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Год_выпуска> Год_выпуска { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<КПП> КПП { get; set; }
        public virtual DbSet<Марка_авто> Марка_авто { get; set; }
        public virtual DbSet<Модель_авто> Модель_авто { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Тарифы> Тарифы { get; set; }
        public virtual DbSet<Тип_кузова> Тип_кузова { get; set; }
    }
}
