//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Сотрудники
    {
        public int id_сотрудника { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string Рабочий_телефон { get; set; }
        public string Email { get; set; }
        public string Логин_пользователя { get; set; }
    }
}
