//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Автомобили
    {
        public int id_автомобиля { get; set; }
        public string номерной_знак { get; set; }
        public string Модель { get; set; }
        public string Статус { get; set; }
    }
}
