//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аренда
    {
        public int id_аренда { get; set; }
        public Nullable<int> id_автомобиля { get; set; }
        public Nullable<int> id_пользователь { get; set; }
        public Nullable<int> id_тарифа { get; set; }
        public Nullable<int> стоимость { get; set; }
        public Nullable<System.DateTime> Дата_начала_аренды { get; set; }
        public Nullable<System.DateTime> Дата_окончания_аренды { get; set; }
    
        public virtual Автомобиль Автомобиль { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Тарифы Тарифы { get; set; }
    }
}
