//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Год_выпуска
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Год_выпуска()
        {
            this.Модель_авто = new HashSet<Модель_авто>();
        }
    
        public int id_год_выпуска { get; set; }
        public Nullable<int> Год { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Модель_авто> Модель_авто { get; set; }
    }
}
