//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvtoPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public int id_сотрудника { get; set; }
        public Nullable<int> id_пользователь { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string Рабочий_телефон { get; set; }
        public string Email { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
